app:
    resource: '@AppBundle/Controller/'
    type: annotation
    
main:
    resource: "@MainBundle/Controller"
    type: annotation
    prefix: manitra

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
